package logic

const MainMenuKeyboard_fiatCurrency = "Узнать курс фиатной валюты"
const MainMenuKeyboard_calculateFiatCyrrencyes = "Калькулятор фиатных валют"
const MainMenuKeyboard_goldMakhachkala = "Цена золота в Махачкале"
const ChoiceOperation = "choiceOperation"
const ChoiceFirstFiatCurrency = "choiceFirstFiatCurrency"
const ChoiceFiatAmount = "choiceFiatAmount"
const ChoiceOneFiatCurrency = "choiceOneFiatCurrency"
const ChoiceSecondFiatCurrency = "choiceSecondFiatCurrency"
const CourseFiatCurrency = "courseFiatCurrency"
const FirstFiatCyrrency = "firstFiatCyrrency"
const SecondFiatCyrrency = "secondFiatCyrrency"
const FiatAmount = "fiatAmount"
const Start = "start"
const GoldMakhachkala = "goldMakhachkala"
const ChoiceGoldMakhachkala = "choiceGoldMakhachkala"
const GoldRussia = "goldRussia"
const ChoiceGoldRussia = "choiceGoldRussia"
