name: Deploy-ubuntu

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend
        id: docker_build_backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          tags: ivan556/currency_golang_bot

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: vardidze.ru
          username: rostom
          key: ${{ secrets.SSH_PRYVATE_KEY }}
          script: |
            docker pull ivan556/currency_golang_bot &&\
            docker run --name go_currency_bot --restart=on-failure -d ivan556/currency_golang_bot

