name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test-lint:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test bot
        run: go test -v ./test

