name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test-lint:
    name: Test
    runs-on: ubuntu-22.04
    env:
    TZ: Europe/Moscow    # Установка переменной окружения TZ на Europe/Moscow
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set system timezone
        run: |
          sudo ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
          sudo dpkg-reconfigure -f noninteractive tzdata

      - name: test bot
        run: go test -v ./test

